version: "3"

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

services:
    ## PHP-FPM
    php-fpm:
        container_name: alan_php-fpm
        build: 
            context: ./php-fpm
            args: 
                - TIMEZONE=${TIMEZONE}
        volumes: 
            - ${WEBSITES_DIR}:/home/www
            - ${PHP_FPM_LOG_DIR}:/var/log/php-fpm
            - ${PHP_FPM_INI}:/usr/local/etc/php
        ports: 
            - "${PHP_FPM_PORT}:9000"
            - "${SWOFT_PORT}:18306"
        networks:
            - backend

        
    ## Nginx
    nginx:
        container_name: alan_nginx
        build:
            context: ./nginx
            args: 
                - TIMEZONE=${TIMEZONE}
        volumes: 
            - ${WEBSITES_DIR}:/home/www
            - ${NGINX_LOG_DIR}:/var/log/nginx
            - ${NGINX_CONF}:/etc/nginx/conf.d
        ports: 
            - "${NGINX_PORT}:80"
        depends_on:
            - php-fpm
        networks:
            - frontend
            - backend

    
    ## MySQL
    mysql:
        container_name: alan_mysql
        build: 
            context: ./mysql
            args: 
                - TIMEZONE=${TIMEZONE}
        volumes: 
            - ${MYSQL_DATA}:/var/lib/mysql
            - ${MYSQL_CONF}:/etc/mysql/conf.d
        ports: 
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
        networks:
            - backend

    
    ## Redis
    redis:
        container_name: alan_redis
        build: 
            context: ./redis
        ports: 
            - "${REDIS_PORT}:6379"
        networks:
            - backend
