version: "3"

networks:
    alan_php_env:

services:
    ## php-fpm
    php-fpm:
        container_name: alan_php-fpm
        build: 
            context: ./php-fpm
        volumes: 
            - ${WEBSITES_DIR}:/home/www
            - ${PHP_FPM_LOG_DIR}:/var/log/php-fpm
            - ${PHP_FPM_INI}:/usr/local/etc/php
        ports: 
            - "${PHP_FPM_PORT}:9000"
            - "${SWOFT_PORT}:18306"
        networks:
            - alan_php_env

        
    ## Nginx
    nginx:
        container_name: alan_nginx
        build:
            context: ./nginx
        volumes: 
            - ${WEBSITES_DIR}:/home/www
            - ${NGINX_LOG_DIR}:/var/log/nginx
            - ${NGINX_CONF}:/etc/nginx/conf.d
        ports: 
            - "${NGINX_PORT}:80"
        networks:
            - alan_php_env
        depends_on:
            - php-fpm

    
    ## MySQL
    mysql:
        container_name: alan_mysql
        build: 
            context: ./mysql
        volumes: 
            - ${MYSQL_DATA}:/var/lib/mysql
            - ${MYSQL_CONF}:/etc/mysql/conf.d
        ports: 
            - "${MYSQL_PORT}:3306"
        networks:
            - alan_php_env

    
    ## Redis
    redis:
        container_name: alan_redis
        build: 
            context: ./redis
        ports: 
            - "${REDIS_PORT}:6379"
        networks:
            - alan_php_env
